# fly.toml app configuration file generated for full-stack-open-pokedex-joulukuu on 2023-12-23T22:27:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "full-stack-open-pokedex-joulukuu"
primary_region = "arn"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false
    processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
